---
docker:
  latest: true
  alias: dnsmasq
  version: '{{ VERSION }}'
  registry: docker.io
  filepath: docker
  filename: Dockerfile.fedora
  build_args:
    - BUILD_TARGETARCH: {{ TARGETARCH }}
    - BUILD_VERSION: '{{ VERSION }}'
    - BUILD_DATE: {{ DATE }}
...
