---
docker:
  latest: true
  version: {{ VERSION }}
  registry: docker.io
  filename: Dockerfile.alpine
  platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  build_args:
    - BUILD_TARGETARCH: {{ TARGETARCH }}
    - BUILD_VERSION: {{ VERSION }}
    - BUILD_DATE: {{ DATE }}
...
