---
environments:
  dev:
    docker:
      tags:
        - 0.0.4
        - latest
      name: dnsmasq
      registry: docker.io
      filename: Dockerfile.debian
      platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
...
