---
docker:
  latest: true
  alias: dnsmasq
  version: '{{ VERSION }}'
  registry: docker.io
  filepath: docker
  filename: Dockerfile.debian
  platforms: linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/amd64
  build_args:
    - BUILD_TARGETARCH: {{ TARGETARCH }}
    - BUILD_VERSION: '{{ VERSION }}'
    - BUILD_DATE: {{ DATE }}
...
