---
docker:
  latest: true
  version: {{ VERSION }}
  registry: docker.io
  filename: Dockerfile.alpine
  platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
  tags:
    - '0'
    - '0.0'
  build_args:
    - BUILD_TARGETARCH: {{ TARGETARCH }}
    - BUILD_VERSION: {{ VERSION }}
    - BUILD_DATE: {{ DATE }}
...
