---
services:
  dns-proxy:
    image: edelux/dns-proxy:latest
    container_name: dns-proxy
    pull_policy: missing
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    tmpfs:
      - /run
      - /tmp
      - /var/run
    ports:
      - '53:53/udp'
    command: >
      --anonymized
      --cachesize=1024
      --server=/default/192.168.122.1
      --server=/ec2.internal/10.18.0.2
      --server=/amazonaws.com/10.18.0.2
      --server=/compute.internal/10.18.0.2
    restart: always
...
