listen_addresses = ['127.0.0.1:5300']

server_names = ['cloudflare']
user_name = 'nobody'

log_level = 0
require_nolog = true
require_nofilter = true

require_dnssec = true
dnscrypt_servers = false
doh_servers = true

[sources]
  [sources.'public-resolvers']
    url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
    cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
