---
name: Build and Push Docker image
run-name: Build and Push

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.github/**'
      - 'docker/compose.yaml'

jobs:
  validate-yaml-config:
    if: ${{ !(
      github.ref == 'refs/heads/main' &&
      startsWith(github.event.head_commit.message, 'Merge pull request') &&
      (
        contains(github.event.head_commit.message, '/feature/') ||
        contains(github.event.head_commit.message, '/feat/') ||
        contains(github.event.head_commit.message, '/fix/')
      )
    ) }}
    uses: edelux/cicd-test-lint/.github/workflows/validate-yaml-config.yaml@main
    with:
      config_path: config.yaml

    permissions:
      actions: read
      contents: read

  build-and-push:
    needs: validate-yaml-config
    if: ${{ needs.validate-yaml-config.result == 'success' }}
    uses: edelux/cicd-build-push/.github/workflows/build_push.yaml@main
    with:
      config_path: config.yaml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    permissions:
      id-token: write
      contents: read
...
