---
name: Build and Push Docker image
run-name: Build and Push

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.github/**'

  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.github/**'

jobs:
  validate-yaml-config:
    uses: edelux/cicd-test-lint/.github/workflows/validate-yaml-config.yaml@main
    with:
      config_path: config.yaml

    permissions:
      actions: read
      contents: read

  build-and-push:
    needs: validate-yaml-config
    uses: edelux/cicd-build-push/.github/workflows/build_push.yaml@main
    with:
      config_path: config.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    permissions:
      id-token: write
      contents: read
...
